### PR TITLE
remove asl_imu_compass from cmakelists file

### PR DESCRIPTION
**Pull request by fmina**

### CODE REVIEW

**Comment by ffurrer** [comment]
continuous integration?
@helenol or @alexmillane can you set up jenkins for this repo?

**Comment by ffurrer** [comment]
@fmina I guess this looks good, but let's wait until this is CI is set up.

**Comment by marija-p** [comment]
LGTM, thanks

**Comment by helenol** [comment]
tes this please

**Comment by enricgalceran** [comment]
@fmina this looks build-tested and ready to merge. Thanks.

**Pull request merged**
